[Service]
# The minus sign (-) means systemd won't fail the whole boot process if this specific command errors out.
ExecStartPost=-/usr/bin/flatpak remote-modify --user --filter=/etc/bog/flatpak-filter.txt flathub