---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bog
description: My personal uBlue/Fedora image.

# the base image to build on top of (FROM) and the version tag to use
# base-image: ghcr.io/ublue-os/base-nvidia:latest
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - network-manager-applet
        - distrobox
        - gnome-shell
        - gnome-session
        - gnome-settings-daemon
        - gnome-control-center
        - gnome-console
        - gdm
        - xdg-desktop-portal-gnome
        - nautilus
        - gnome-system-monitor
        - steam
        - dconf
        - nano
        - micro
    remove:
      packages:
        - toolbox
        - htop
        - nvtop

  - type: script
    scripts:
      - dconf-update.sh
      # below for future script, maybe post-first-boot script if bluebuild supports that
      # distrobox create --pull -Y -n arch -i archlinux:latest -ap "base-devel git" -- bash -c "git clone https://aur.archlinux.org/yay-bin.git;cd yay-bin;makepkg -si"

  #- type: default-flatpaks
    #configurations:
      #- notify: true # Send notification after install/uninstall is finished (true/false)
      # scope: system
      # # If no repo information is specified, Flathub will be used by default
      # install: # system flatpaks we want all users to have and not remove
      #- scope: system

  # gotta figure out some way to have restrictions on the copy of bazaar (or download it and set it, idk whatever bazzite does lol)
  - type: default-flatpaks
    configurations:
      #- scope: user
      #  repo:
      #    title: Flathub (user)
      #  install:
      #    - dev.vencord.Vesktop
      #    - org.signal.Signal
      #    - org.nickvision.tubeconverter
      #    - com.google.Chrome
      #    - com.spotify.Client
      - notify: true
        scope: system
        repo:
          title: Flathub (system)
        install:
          - io.github.kolunmi.Bazaar
          - ca.desrt.dconf-editor
          - org.mozilla.firefox
          - com.github.tchx84.Flatseal
          - com.ranfdev.DistroShelf
          - org.gnome.Loupe
          - org.gnome.Papers
          - org.gnome.Weather
          - org.gnome.clocks
          - org.gnome.font-viewer
          - org.gnome.Calculator
          - org.gnome.Contacts
          - org.gnome.Calendar
          - org.gnome.Logs
          - org.gnome.FileRoller
          - org.gnome.TextEditor
          - org.gnome.NetworkDisplays
          - org.gnome.Boxes
          - org.gnome.Boxes.Extension.OsinfoDb
          - io.github.flattool.Ignition
          - com.mattjakeman.ExtensionManager
          - io.github.celluloid_player.Celluloid
          - com.usebottles.bottles
          - com.vysp3r.ProtonPlus
          - org.onlyoffice.desktopeditors
          #- org.kde.krita
          #- org.kde.kdenlive
          #- org.audacityteam.Audacity
          #- com.obsproject.Studio
          #- com.github.qarmin.czkawka
          #- me.timschneeberger.jdsp4linux


  - type: fonts
    fonts:
      google-fonts:
        - Inter
      #url-fonts:
      #  - name: CustomFont
      #    url: https://example.com/my-font.otf
      #  - name: CompanyFonts
      #    url: https://company.com/fonts.tar.gz

  - type: gnome-extensions
    install:
      - 3088 # extension list
      - 615 # appindicator support
      - 8 # places menu
      - 1319 # gsconnect
      - 517 # caffeine
      - 5263 # gtk desktop icons ng (ding)
      - 600 # launch new instance
      - 36 # lock keys
      #- 5721 # clipboard indicator
    #uninstall:
    #  - GSConnect

  - type: signing # this sets up the proper policy & signing files for signed images to work fully