---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bog
description: My personal uBlue/Fedora image.

# the base image to build on top of (FROM) and the version tag to use
# base-image: ghcr.io/ublue-os/base-nvidia
# image-version: latest # latest is also supported if you want new updates ASAP
base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:

  #- type: files
    #files:
      #- source: system
        #destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        # Core Plasma Desktop - Minimal Set
        - plasma-desktop
        - plasma-workspace
        - plasma-workspace-wayland
        - plasma-workspace-x11      # ADD: X11 session support
        - kwin
        
        # Display Manager
        - sddm
        - sddm-breeze
        - sddm-kcm
        - sddm-wayland-plasma
        
        # Plasma System Settings & Integration
        - systemsettings
        - polkit-kde
        - kscreen
        - plasma-nm
        - plasma-pa
        - bluedevil
        
        # Discover Store with Flatpak Support
        - plasma-discover
        - plasma-discover-flatpak
        - plasma-discover-notifier
        - flatpak
        
        # CRITICAL: Missing Discover dependencies (Fedora packaging bug)
        - kf6-purpose              # ADD: Required for Discover QML modules
        - kf6-kitemmodels          # ADD: Required for Discover item models
        
        # Qt6 Components
        - qt6-qtbase-gui           # ADD: Qt6 GUI support
        
        # Essential Applications
        - dolphin
        - konsole
        
        # Utilities & Tools
        - distrobox
        - steam
        - nano
        - micro
    remove:
      packages:
        - toolbox

  # - type: script
    # scripts:
      # - dconf-update.sh
      # below for future script, maybe post-first-boot script if bluebuild supports that
      # - distrobox-preinstall.sh
      # distrobox create --pull -Y -n arch -i archlinux:latest -ap "base-devel git" -- bash -c "git clone https://aur.archlinux.org/yay-bin.git;cd yay-bin;makepkg -si"

  - type: systemd
      system:
        enabled:
          - sddm.service

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        repo:
          title: Flathub (System)
        install:
          - org.mozilla.firefox
          - com.github.tchx84.Flatseal
          - io.github.DenysMb.Kontainer
          - org.videolan.VLC
          - com.usebottles.bottles
          - com.vysp3r.ProtonPlus
          - org.onlyoffice.desktopeditors
          - org.kde.krita
          - org.kde.kdenlive
          - org.audacityteam.Audacity
          - com.obsproject.Studio
          #- com.github.qarmin.czkawka
          - me.timschneeberger.jdsp4linux

  - type: signing # this sets up the proper policy & signing files for signed images to work fully