ARG BASE_IMAGE_URL=ghcr.io/ublue-os/base-main
ARG IMAGE_TAG=latest

FROM ${BASE_IMAGE_URL}:${IMAGE_TAG}

# Copy configuration and scripts
COPY config /tmp/config
COPY config/scripts/*.sh /tmp/

# Install VM guest tools
RUN rpm-ostree install qemu-guest-agent open-vm-tools spice-vdagent

# Run other scripts
RUN /bin/bash /tmp/install-gnome.sh
RUN /bin/bash /tmp/setup-distrobox.sh
RUN /bin/bash /tmp/configure-flatpak.sh
RUN /bin/bash /tmp/cleanup.sh

LABEL variant="vm"
LABEL org.opencontainers.image.title="Bog VM"
LABEL org.opencontainers.image.description="Custom immutable Linux with minimal GNOME and VM guest tools"