name: Bluebuild Release

on:
  schedule:
    - cron: '0 10 * * 3' # Wednesday at 10AM UTC
  push: # Any pushes to the repo (should consider specific to main branch)
    paths-ignore: # Don't rebuild if only documentation has changed
      - "**.md"
  pull_request: # Successful pull request
  workflow_dispatch: # Manual rebuild dispatches

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  push-update:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: true # Stop GitHub from continuing all matrix builds if one fails.
      matrix:
        recipe:
          - recipe.yml
          - recipe-nvidia.yml
    steps:
      # The build is fully handled by the reusable GitHub action
      - name: Build Image
        uses: blue-build/github-action@v1.12.0
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true # enabled by default, disable if your image is small and you want faster builds